### PR TITLE
Fix issues in flow control code and associated tests

### LINKED ISSUE #637: pio_swapm() test coverage shows that it is not being tested
We have a function pio_swapm() in pio_spmd.c.

It is like MPI_Alltoallw() with flow control.

But in our tests, we never use the flow control. I'm not sure if we do in the code either. (I believe this is an intended optimization that has not yet be achieved.)

Is this similar to the flow control that Jayesh just added? Or is that different?

### LINKED ISSUE #645: is documentation of ceil2() function in pio_spmd.c correct?
When writing a test for the ceil2() function, I found that it's documentation is wrong. It says:

> Returns the smallest power of 2 greater than i.

But it should be

> greater than or equal to i.

Mistake in code? Or mistake in documentation?

This function is used only one place, in pio_swapm().

### PR DESCRIPTION
**Pull request by jayeshkrishna**
This PR includes,
* Fixes to the fortran pio rearranger tests to use all the rearranger options
* More Fortran tests for testing rearranger options
* Fixes to the pio flow control code
* Minor doc fixes and logging

Fixes #637 
Fixes #645

### CODE REVIEW

File: src/clib/pio_spmd.c [hunk 1]
```diff
@@ -291,7 +302,7 @@ int pio_swapm(void *sendbuf, int *sendcounts, int *sdispls, MPI_Datatype *sendty
              * used to choose between mpi_irsends and mpi_isends - the default
              * is still mpi_irsend
              */
-            if (isend)
+            if (handshake && isend)
```
Comment (jedwards4b) [inline src/clib/pio_spmd.c]: This change doesn't make any sense to me.  The code for isend here is the same whether or not handshake is true, except that you removed the ifdef USE_MPI_ISEND_FOR_FC

Comment (jayeshkrishna) [inline src/clib/pio_spmd.c]: I don't think we can guarantee that a recv is posted without an application handshake (since we post recvs in blocks).
