### PR TITLE
Got tests to work with async

### LINKED ISSUE #238: Setting error handler not currently working with async
Currently setting the error handler does not work with async.

### LINKED ISSUE #348: Test code in test_names() in test_pioc.c doesn't work with async
The test_names() function in test_pioc.c works with non-async, but not async.

Part of #205.

### LINKED ISSUE #349: Test code in test_deletefile() doesn't work for async
In test_pioc.c the test_deletefile() tests run on non-async, but hangs on async.

Part of #205.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #349.

Fixes #348.

Fixes #238.

Contributes to #205.

This PR contains some fixes and turns on async testing for all the tests in test_pioc.c (many of those tests, until now, were only working for non-async cases.)

Now all the tests in test_pioc.c are run for both async and non-async cases.

I have merged to develop for testing.

### CODE REVIEW

File: src/clib/pio_file.c [hunk 1]
```diff
@@ -402,14 +402,15 @@ int PIOc_deletefile(int iosysid, const char *filename)
...
-            LOG((2, "Bcast len = %s filename = %s", len, filename));
+            LOG((2, "Bcast len = %d filename = %s", len, filename));
         }
 
         /* Handle MPI errors. */
         if ((mpierr2 = MPI_Bcast(&mpierr, 1, MPI_INT, ios->comproot, ios->my_comm)))
             return check_mpi2(ios, NULL, mpierr2, __FILE__, __LINE__);
         if (mpierr)
             return check_mpi2(ios, NULL, mpierr, __FILE__, __LINE__);
+        LOG((3, "done hanlding errors mpierr = %d", mpierr));
```
Comment (jedwards4b) [inline src/clib/pio_file.c]: spelling :-)
