### PR TITLE
Type conversion for attributes

### LINKED ISSUE #467: Attribute type conversions will not work
The current code will not correctly handle the case where an attribute type conversion is taking place.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #467.

I will merge to develop for testing.

### CODE REVIEW

File: src/clib/pio_msg.c [hunk 1]
```diff
@@ -512,38 +515,45 @@ int att_put_handler(iosystem_desc_t *ios)
...
         return check_mpi2(ios, NULL, mpierr, __FILE__, __LINE__);
-    if (!(op = malloc(attlen * typelen)))
+    if ((mpierr = MPI_Bcast(&memtype_len, 1, MPI_OFFSET, 0, ios->intercomm)))
+        return check_mpi2(ios, NULL, mpierr, __FILE__, __LINE__);
+
+    /* Allocate memory for the attribute data. */
+    if (!(op = malloc(attlen * memtype_len)))
         return pio_err(ios, NULL, PIO_ENOMEM, __FILE__, __LINE__);
-    if ((mpierr = MPI_Bcast((void *)op, attlen * typelen, MPI_BYTE, 0, ios->intercomm)))
+    if ((mpierr = MPI_Bcast((void *)op, attlen * memtype_len, MPI_BYTE, 0, ios->intercomm)))
```
Comment (jedwards4b) [inline src/clib/pio_msg.c]: op is already declared void * - this cast isn't needed.

File: tests/cunit/test_pioc.c [hunk 2]
```diff
@@ -665,12 +739,17 @@ int test_names(int iosysid, int num_flavors, int *flavor, int my_rank,
...
 
         /* Define a global attribute. */
-        int att_val = 42;
+        int att_val = ATT_VAL;
+        float float_att_val = ATT_VAL;
         if ((ret = PIOc_put_att_int(ncid, NC_GLOBAL, ATT_NAME, PIO_INT, 1, &att_val)))
             ERR(ret);
+        if ((ret = PIOc_put_att_float(ncid, NC_GLOBAL, ATT_NAME2, PIO_FLOAT, 1, &float_att_val)))
+            ERR(ret);
+        /* if ((ret = PIOc_put_att_int(ncid, NC_GLOBAL, ATT_NAME2, PIO_FLOAT, 1, &att_val))) */
```
Comment (jedwards4b) [inline tests/cunit/test_pioc.c]: why the commented code?

Comment (edhartnett) [inline tests/cunit/test_pioc.c]: That's how I discovered that conversions did not work. ;-)

I have removed that line in my current branch. It's not needed. I am adding systematic tests for attribute type conversion.
