### PR TITLE
Fix pointless check in darray functions, added comments

### LINKED ISSUE #715: Useless check in PIOc_write_darray()
I see this useless check:

```
    /* Get var description. */
    if (!(vdesc = file->varlist + vid))
        return pio_err(ios, file, PIO_EBADID, __FILE__, __LINE__);
    LOG((2, "vdesc record %d ndims %d nreqs %d", vdesc->record, vdesc->ndims, vdesc->nreqs));

```

What would be useful would be to check that vid is valid, if it can be done in a very efficient way.

### PR DESCRIPTION
**Pull request by edhartnett**
Fixes #715.

I will merge to develop for testing.

### CODE REVIEW

File: src/clib/pio_darray_int.c [hunk 1]
```diff
@@ -490,10 +488,11 @@ int pio_write_darray_multi_nc(file_desc_t *file, int nvars, const int *vid, int
     GPTLstart("PIO:write_darray_multi_nc");
 #endif
 
-    /* Get file and variable info. */
+    /* Get pointer to iosystem. */
     ios = file->iosystem;
-    if (!(vdesc = file->varlist + vid[0]))
-        return pio_err(ios, file, PIO_EBADID, __FILE__, __LINE__);
+
+    /* Point to var description scruct for first var. */
```
Comment (jedwards4b) [inline src/clib/pio_darray_int.c]: struct

File: src/clib/pio_darray_int.c [hunk 2]
```diff
@@ -1434,12 +1466,15 @@ int pio_read_darray_nc_serial(file_desc_t *file, io_desc_t *iodesc, int vid,
...
 
+                /* Now get each region of data. */
                 loffset = 0;
                 for (int regioncnt = 0; regioncnt < maxregions; regioncnt++)
                 {
+                    /* Get pointer where data should go. */
                     bufptr = (void *)((char *)iobuf + tsize * loffset);
                     regionsize = 1;
 
+                    /* ??? */
```
Comment (jedwards4b) [inline src/clib/pio_darray_int.c]: The decomposition may not use all of the active io tasks rtask here is the io task rank and ios->num_iotasks is the number of iotasks actually used in this decomposition.

Comment (edhartnett) [inline src/clib/pio_darray_int.c]: OK, thanks, I will add this comment in my next PR...
