### PR TITLE
tested PIOc_Set_File_Error_Handling and also fixed some error handlin…

### LINKED ISSUE #509: Test PIOc_Set_File_Error_Handling()
We may be removing it, but until we do, let's test it.

### PR DESCRIPTION
**Pull request by edhartnett**
…g in it

Fixes #509.

I will merge to develop for testing.

### CODE REVIEW

File: src/clib/pioc.c [hunk 1]
```diff
@@ -88,7 +88,7 @@ int PIOc_Set_File_Error_Handling(int ncid, int method)
     /* Check that valid error handler was provided. */
     if (method != PIO_INTERNAL_ERROR && method != PIO_BCAST_ERROR &&
         method != PIO_RETURN_ERROR)
-        return pio_err(file->iosystem, file, PIO_EINVAL, __FILE__, __LINE__);
+        piodie("Invalid error hanlder method", __FILE__, __LINE__);
```
Comment (jedwards4b) [inline src/clib/pioc.c]: spelling typo

Comment (edhartnett) [inline src/clib/pioc.c]: No it's an alternate fact.
