### PR TITLE
More tests, plus some fixes to PIOc_inq_var_chunksizes()

### LINKED ISSUE #439: Need tests for PIOc_iosystem_is_active/PIOc_File_is_Open from pioc.c

### LINKED ISSUE #444: Test invalid parameters with PIOc_Init_Async()/PIOc_Init_Intracomm()

### PR DESCRIPTION
**Pull request by edhartnett**
More tests, and a fix.

Fixes #439.
Fixes #444.
Work on #430.
Work on #433.

I have merged to develop for testing.

### CODE REVIEW

File: tests/cunit/test_async_simple.c [hunk 1]
```diff
@@ -54,6 +54,16 @@ int main(int argc, char **argv)
         /* Is the current process a computation task? */
         int comp_task = my_rank < NUM_IO_PROCS ? 0 : 1;
 
+        /* Check for invalid values. */
+        if (PIOc_Init_Async(test_comm, NUM_IO_PROCS, NULL, COMPONENT_COUNT,
+                            num_procs, NULL, NULL, NULL, NULL) != PIO_EINVAL)
+            ERR(ERR_WRONG);
+        if (PIOc_Init_Async(test_comm, NUM_IO_PROCS, NULL, -1,
+                            num_procs, NULL, NULL, NULL, iosysid) != PIO_EINVAL)
+        if (PIOc_Init_Async(test_comm, NUM_IO_PROCS, NULL, COMPONENT_COUNT,
```
Comment (jedwards4b) [inline tests/cunit/test_async_simple.c]: Did you miss an ERR(ERR_WRONG) here?
