### PR TITLE
fix issue with non iotasks calling flush

### LINKED ISSUE #719: recent commit breaks cesm
I have been testing in cesm, most recently trying to track down a bug in netcdf4 on the ncar cheyenne system.   I recently updated to the head of master and got a new error: 

0:ERROR: 0 NetCDF: Not a valid ID err_num = -33 fname = /glade/scratch/jedwards/forbrian/cesm2_0_alpha06/cime/externals/pio2/src/clib/pio_darray.c line = 261

I've traced this back to commit f9bee9e Merge pull request #680 from NCAR/ejh_ret_codes

I do not get this error in commit 6ad90b0 Merge pull request #651 from NCAR/jayeshkrishna/more_1d_tests

### PR DESCRIPTION
**Pull request by jedwards4b**
Non-iotasks were calling ncmpi functions and thus returning an invalid file id error.
I have merged to develop for testing
Fixes #719

### CODE REVIEW

File: src/clib/pio_darray_int.c [hunk 1]
```diff
@@ -1521,8 +1521,7 @@ int flush_output_buffer(file_desc_t *file, bool force, PIO_Offset addsize)
 
     /* Find out the buffer usage. If I check the turn code, some tests fail. ??? */
     if ((ierr = ncmpi_inq_buffer_usage(file->fh, &usage)))
-        return ierr;
-    /*return pio_err(ios, file, PIO_EBADID, __FILE__, __LINE__);*/
+	return ierr;
```
Comment (edhartnett) [inline src/clib/pio_darray_int.c]: Can this return code be handled with pio_err?

Comment (jedwards4b) [inline src/clib/pio_darray_int.c]: Was this pio_err commented out because non-io tasks were getting here?  Perhaps it can be put back in.

Comment (edhartnett) [inline src/clib/pio_darray_int.c]: That makes a lot of sense!

It was commented out, as indicated by the comment, because when I put it in, some tests failed. I had not yet figured out why, but it could be the same bug you found.

Please check it, because, if true, it means that we already have a test that detects that problem. ;-)

**Comment by jedwards4b** [comment]
I replaced with pio_err, ran tests on my machine to confirm it works and pushed to develop.

**Comment by edhartnett** [comment]
OK if I merge this? It has passed cdash testing...
